local druid = require("druid.druid")
local broadcast = require("main.modules.system.broadcast")
local InventoryWindow = require("main.gui.components.inventory_window.inventory_window")
local player_inv = require("main.modules.player.player_inventory")
local drag_manager = require("main.gui.components.managers.drag_manager")
local window_manager = require("main.gui.components.managers.window_manager")
local tooltip_manager = require("main.gui.components.managers.tooltip_manager")
local h_touch = hash("touch")

function init(self)
    print("DEBUG: Inventory Window Address is:", msg.url())
    msg.post(".", "acquire_input_focus")

    self.druid = druid.new(self)
    self.inventory_window = self.druid:new(InventoryWindow, "", player_inv)

    self.broadcast_handler = function(data)
        if data.message_id == hash("inventory_changed") then
            print("GET BRODCAST IN INVENTORY")
            self.inventory_window:refresh()
        end
    end
    broadcast.subscribe("inventory_events", self.broadcast_handler)
end

function final(self)
  broadcast.unsubscribe("inventory_events", self.broadcast_handler)
end

function update(self, dt)
    if self.inventory_window then
        -- 1. Системный апдейт (ховеры окна для блокировки мира + Dirty Flag)
        self.inventory_window:update(dt, window_manager.mouse_x, window_manager.mouse_y)

        -- 2. Тултипы (используем системный метод из базы)
        local mx, my = tooltip_manager.mouse_x, tooltip_manager.mouse_y
        
        -- Вызываем метод БАЗЫ, который внутри себя вызовет get_hover_data окна
        local hovered = self.inventory_window:handle_hover(mx, my)
        
        -- Если ничего не ховерится, но мышь над окном — прячем тултип
        if not hovered and gui.pick_node(self.inventory_window.root, mx, my) then
            tooltip_manager.hide()
        end
    end
end

function on_message(self, message_id, message, sender)
    -- ГОЛОЕ ЗАКРЫТИЕ (от менеджера или кнопки Esc)
    if message_id == hash("close_window") then
        self.inventory_window:close() -- Твой метод модуля

    -- ПЕРЕКЛЮЧЕНИЕ (от кнопки "C" или кнопки в HUD)
    elseif message_id == hash("toggle_inventory_window") then
        self.inventory_window:toggle()

    elseif message_id == hash("refresh") then
        if self.inventory_window and self.inventory_window:is_visible() then
            self.inventory_window.static_grid:refresh()
        end
    end
end


function on_input(self, action_id, action)
    if not self.inventory_window or not self.inventory_window:is_visible() then
        return self.druid:on_input(action_id, action)
    end

    local handled = self.druid:on_input(action_id, action)

    if drag_manager.is_dragging() then
        if not action_id or action_id == h_touch then
            drag_manager.update(action.x, action.y)
            if gui.pick_node(self.inventory_window.root, action.x, action.y) then
                drag_manager.set_over_gui(true)
            end
        end

        if action_id == h_touch and action.released then
            -- Пробуем дроп в инвентарь или куклу
            if self.inventory_window.static_grid:on_drop(action.x, action.y) then return true end

            -- Отмена драга над окном
            if gui.pick_node(self.inventory_window.root, action.x, action.y) then
                drag_manager.finish(nil, nil)
                return true
            end
        end
    end

    return handled
end

-- function on_input(self, action_id, action)
--     if not self.character_window or not self.character_window:is_visible() then
--         return self.druid:on_input(action_id, action)
--     end
--
--     local handled = self.druid:on_input(action_id, action)
--
--     if not action_id then
--         -- Обновляем драг и НЕ возвращаем true
--         if drag_manager.is_dragging() then
--             drag_manager.update(action.x, action.y)
--             if gui.pick_node(self.inventory_window.root, action.x, action.y) then
--                 drag_manager.set_over_gui(true)
--             end
--         end
--         return handled -- Скорее всего false
--     end
--
--     -- 2. КЛИКИ И ДРАГ (action_id ~= nil)
--     if action_id == h_touch then
--         if drag_manager.is_dragging() then
--             -- Обновляем позицию иконки при зажатой кнопке
--             drag_manager.update(action.x, action.y)
--
--             -- Проставляем флаг GUI
--             if gui.pick_node(self.inventory_window.root, action.x, action.y) then
--                 drag_manager.set_over_gui(true)
--             end
--
--             -- ЛОГИКА ОТПУСКАНИЯ (DROP)
--             if action.released then
--                 print("CHAR: Released")
--                 if self.inventory_window.static_grid:on_drop(action.x, action.y) then return true end
--
--                 if gui.pick_node(self.inventory_window.root, action.x, action.y) then
--                     drag_manager.finish(nil, nil)
--                     return true
--                 end
--             end
--         end
--     end
--
--     return handled
-- end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
