function init(self)
    -- Активируем камеру
    msg.post("#camera1", "acquire_camera_focus")
    print("Camera activated")
end

function update(self, dt)
     local player_pos = go.get_position("player")
    
    -- Округляем координаты до целых пикселей
    -- Это предотвратит отрисовку тайлов "между" пикселями монитора
    -- player_pos.x = math.floor(player_pos.x)
    -- player_pos.y = math.floor(player_pos.y)
    
    go.set_position(player_pos)    
end
