local settings = require("main.modules.settings")

function init(self)
	  msg.post(".", "acquire_input_focus")
    self.pressed = false
    
    -- Подписываемся на обновление позиции мыши
    self.mouse_x = 0
    self.mouse_y = 0
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
    -- Обновляем позицию курсора каждый кадр
    --local camera = go.get_id("camera")
    local player_pos = go.get_position("player")
    local w = settings.resolution.width
    local h = settings.resolution.height
    
    local world_x = player_pos.x + (self.mouse_x - w / 2)
    local world_y = player_pos.y + (self.mouse_y - h / 2)
    
    go.set_position(vmath.vector3(world_x, world_y, 0))      
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
    if message_id == hash("collision_response") and self.pressed then
        print("Clicked on:", message.other_id)
        
        -- Проверяем дистанцию до предмета
        local player_pos = go.get_position("player")
        local item_pos = go.get_position(message.other_id)
        local dist = vmath.length(player_pos - item_pos)
        
        if dist < 50 then
            -- Близко — сразу подбираем
            msg.post(message.other_id, "click")
        else
            -- Далеко — отправляем игрока к предмету
            msg.post("player", "move_to_item", { item_id = message.other_id })
        end
    end	  
end

function on_input(self, action_id, action)
	  -- Сохраняем позицию мыши
    if action.x and action.y then
        self.mouse_x = action.x
        self.mouse_y = action.y
    end
    
    -- Запоминаем нажатие
    if action_id == hash("touch") then
        self.pressed = action.pressed
    end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end


