components {
  id: "cursor"
  component: "/main/player/cursor.script"
}
embedded_components {
  id: "cursor_collision"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"mouse\"\n"
  "mask: \"unit\"\n"
  "mask: \"container\"\n"
  "mask: \"item_loot\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 1\n"
  "  }\n"
  "  data: 1.0\n"
  "}\n"
  "event_collision: false\n"
  "event_contact: false\n"
  ""
}
