function init(self)
    msg.post(".", "acquire_input_focus")
    self.item_id = "unknown"  -- обычная переменная
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function late_update(self, dt)
	-- This function is called at the end of update cycle but before render
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	  if message_id == hash("set_item_id") then
        self.item_id = message.item_id
        print("Item ID set to:", self.item_id)
    end
    
    if message_id == hash("pickup") then
        print("Pickup message received for:", self.item_id)
        msg.post("world", "pickup_item", { item_id = self.item_id })
    end
end

-- function on_input(self, action_id, action)
--     print("Input received:", action_id, action.pressed, action.released)
--     if action_id == hash("touch") and action.pressed then
--          print("Picking up:", self.item_id)
--         -- Отправляем сообщение в мир или напрямую в инвентарь
--         msg.post("world", "pickup_item", { item_id = self.item_id })
--     end
-- end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
