go.property("container_uid", hash(""))
go.property("container_id", hash("chest_common"))
go.property("container_name", hash("container_common_chest_name"))
go.property("columns", 6)
go.property("rows", 4)
go.property("is_lootable", true)
go.property("is_random_loot", true)
go.property("loot_table_id", hash("empty"))

local interaction = require("main.modules.interaction")
local loot_tables = require("main.modules.data.loot_tables")
local containers_state = require("main.modules.game_state.containers_state")
local locales = require("main.modules.data.locales.locale_manager")

local broadcast = require("main.modules.system.broadcast")

local function apply_container_visual(self)
    -- Устанавливаем текст как в lootable_item
    print('name', self.container_name)
    label.set_text("#container_name", locales.get(self.container_name))
    -- msg.post("#container_name", "disable")
end

local function open_container(self)
    -- 1. Пытаемся взять данные из динамического реестра (был ли он уже открыт в этой сессии?)
    local state = containers_state.registry[tostring(self.container_uid)]
    
    -- 2. Если в реестре пусто - значит это ПЕРВОЕ открытие после New Game или билда
    if not state or not state.is_looted then
        print("First time opening or New Game reset. Generating loot...")
        
        -- Генерируем лут по таблице из свойств объекта
        local items = loot_tables.get_loot(self.loot_table_id)
        
        -- Формируем полноценную запись для реестра
        state = {
            name = self.container_name,
            is_looted = true,
            items = items,
            columns = self.columns,
            rows = self.rows
        }

        -- Записываем в динамическую память (теперь это сохранится при save_game)
        containers_state.init(self.container_uid, state)
    end

    -- 3. Теперь state точно содержит предметы
    msg.post("main:/container_window#gui", "open_container_window", {
        container_uid = self.container_uid,
        container_id = self.container_id,
        container_name = self.container_name,
        container_items = state.items,
        columns = state.columns,
        rows = state.rows,
        position = go.get_world_position(),
        player_pos = go.get_position("game_scene:/player")
    })
end


local function close_container(self)
    -- Закрыть окно
    msg.post("hud#gui", "close_container")
end

function init(self)
	  -- msg.post(".", "acquire_input_focus")
    self.go_id = go.get_id()

    -- Если в редакторе пусто, используем координаты как UID (авто-заплатка)
    if self.container_uid == hash("") then
        local p = go.get_position()
        self.container_uid = hash(string.format("c_%d_%d", p.x, p.y))
    end

    containers_state.register_static_config(self.container_uid, {
        name = self.container_name,
        columns = self.columns,
        rows = self.rows,
        loot_table_id = self.container_id,
        items = {} -- пусто по умолчанию
    })

    -- 3. РЕГИСТРАЦИЯ СВЯЗИ (всегда!)
    -- Чтобы рейкаст мог найти UID этого конкретного сундука прямо сейчас
    containers_state.register(self.go_id, self.container_uid)
    apply_container_visual(self)

    msg.post("#container_name", "disable")


    -- Подписываемся на хайлайт
    self.broadcast_handler = function(data)
    -- Теперь 'data' — это таблица, которую мы послали через broadcast.send
        if data.message_id == hash("toggle_interactable_highlight") then
            print('TEST PRINT: Highlight toggled!')

            if data.show then
                go.set_scale(vmath.vector3(1.2, 1.2, 1), self.go_id)
                msg.post(msg.url(nil, self.go_id, "container_name"), "enable")
            else
                go.set_scale(vmath.vector3(1, 1, 1), self.go_id)
                msg.post(msg.url(nil, self.go_id, "container_name"), "disable")
            end
        end
    end

    broadcast.subscribe("world_events", self.broadcast_handler)
end

function final(self)
	  containers_state.unregister(self.go_id)
    broadcast.unsubscribe("world_events", self.broadcast_handler)
end

function update(self, dt)
end

function late_update(self, dt)
end

function fixed_update(self, dt)
end

function on_message(self, message_id, message, sender)
	  if message_id == hash("click") then
        interaction.handle_click(self, 50, function()
            print('container_uid', self.container_uid)
            open_container(self)
        end)
    end

    if message_id == hash("close_window") then
        close_container()
    end
end

function on_input(self, action_id, action)
end

function on_reload(self)
end


