local druid = require("druid.druid")
local HealthBar = require("main.gui.components.health_bar.health_bar")
local ActionBar = require("main.gui.action_bar.action_bar")
local Inventory = require("main.gui.components.inventory.inventory") 

function init(self)
	-- Add initialization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
    -- Инициализируем Druid
    self.druid = druid.new(self)
    
    -- Регистрируем нашу полоску здоровья. 
    -- "health_bar" — это ID Template в Outline твоего hud.gui
    self.action_bar = self.druid:new(ActionBar, "action_bar", self.druid)
    self.hp_bar = self.druid:new(HealthBar, "health_bar")
    self.inventory = self.druid:new(Inventory, "inventory")

    self.msg_handlers = {
        [hash("update_health")] = function(self, message) 
            self.hp_bar:update_health(message.percentage) 
        end,
        
        [hash("toggle_inventory")] = function(self) 
            print('TOGGLE INVENTORY')
            self.inventory:toggle() 
        end
    }

     -- Таблица для on_input (клавиатура/хоткеи)
    self.input_handlers = {
        [hash("toggle_inventory")] = toggle_inventory, -- в input_binding назови его так
        [hash("character_key")] = function(self) self.char_window:toggle() end
    }
    print("HUD initialized")
end



function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
    local handler = self.msg_handlers[message_id]
    if handler then
        handler(self, message)
    end    
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed

    -- Сначала проверяем наши хоткеи
    if action.pressed then
        local handler = self.input_handlers[action_id]
        print('handler', handler)
        if handler then
            handler(self)
            return true -- Прерываем ввод, чтобы Druid не кликал "сквозь" это действие
        end
    end

    return self.druid:on_input(action_id, action)
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
