local druid = require("druid.druid")
local constants_ui = require("main.gui.constants_ui")
local window_manager = require("main.gui.components.managers.window_manager")
local ContextMenu = require("main.gui.components.layers.context_menu_layer.ContextMenu")

function init(self)
    self.render_order = constants_ui.LAYERS.POPUP
    self.is_static = false

    msg.post(".", "acquire_input_focus")
    self.druid = druid.new(self)
    -- Регистрируем наш компонент
    self.menu = self.druid:new(ContextMenu)
    gui.set_render_order(30)
end

function final(self)
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
    if message_id == hash("show_menu") then
        self.menu:show(message.x, message.y, message.type, message.sub_type, message.flags, message.data)

        -- ВЫНОСИМ МЕНЮ В ТОП ВВОДА
        msg.post(".", "acquire_input_focus")

        -- Чтобы ESC закрывал сначала меню
        window_manager.push(self, msg.url(), hash("hide_menu"))
    end

    if message_id == hash("hide_menu") then
        self.menu:hide_ui()
        window_manager.pop(msg.url())
        -- ОБЯЗАТЕЛЬНО ОТДАЕМ ФОКУС, когда меню скрыто
        msg.post(".", "release_input_focus")
    end
end

function on_input(self, action_id, action)
    -- Сначала даем компоненту меню проверить клик "мимо"
    local handled = self.menu:on_input(action_id, action)
    if handled then return true end

    -- Потом отдаем Друиду (для кнопок самого меню)
    return self.druid:on_input(action_id, action)
end

function on_reload(self)
end
