local abilities_db = require("main.modules.data.abilities_db")

go.property("caster_go_id", hash(""))
go.property("target_go_id", hash(""))
go.property("ability_id", hash(""))

function init(self)
    -- Только включаем визуал, спрайты и партиклы
    self.ability_cfg = abilities_db.get_ability(self.ability_id)
    if self.ability_cfg and self.ability_cfg.fx and self.ability_cfg.fx.sprite_animation then
        sprite.play_flipbook("#sprite", hash(self.ability_cfg.fx.sprite_animation))
    end

    pcall(particlefx.play, "#frostbolt_trail") 
end

function final(self)
    -- Стерильный клинап
end

function update(self, dt)
end

function late_update(self, dt)
	-- This function is called at the end of update cycle but before render
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
