local druid = require("druid.druid")
local ContainerWindow = require("main.gui.components.container_window.container_window")
local drag_manager = require("main.gui.drag_manager")
local tooltip_manager = require("main.modules.gui.tooltip_manager")
local window_manager = require("main.modules.gui.window_manager")
local h_touch = hash("touch")

function init(self)
    print("DEBUG: Container Window Address is:", msg.url())

    msg.post(".", "acquire_input_focus")
    self.druid = druid.new(self)

    self.container_window = ContainerWindow.new(self.druid, "", {
        columns = 6,
        rows = 4,
        spacing = 2
    })

    self.container_window:set_visible(false)
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
    -- Если объект окна еще не создан или не проинициализирован
    if not self.container_window or not self.container_window.inventory_grid then
        return
    end
    
    -- Берем координаты из менеджера (которые обновляет world.script)
    local mx = tooltip_manager.mouse_x
    local my = tooltip_manager.mouse_y
    
    local hovered = false
    -- Проверяем инвентарь (если окно открыто)
    if self.container_window:is_visible() then
        if self.container_window.inventory_grid:update_hover(mx, my) then
            hovered = true
        end
    end
    
    -- Если ни один слот ни в одном модуле не поймал мышь
    if not hovered then
        -- Важно: прячем только если мышь была над этим окном
        if gui.pick_node(self.container_window.root, mx, my) then
            tooltip_manager.hide()
        end
    end
end

function on_message(self, message_id, message, sender)
    if message_id == hash("open_container_window") then        
        self.container_window:open(
            message.container_id,
            message.columns,
            message.rows,
            message.position,      -- мирная позиция контейнера
            message.player_pos     -- позиция игрока
        )
        gui.set_render_order(11)
        window_manager.push(msg.url())
    end
    -- ГОЛОЕ ЗАКРЫТИЕ (от менеджера или кнопки Esc)
    if message_id == hash("close_window") then
        if self.container_window:is_visible() then
            self.container_window:close()
            gui.set_render_order(0)
            window_manager.pop(msg.url())
        end
    end
   

    -- elseif message_id == hash("close_container_window") then
    --     if self.container_window then
    --         self.container_window.close() -- Вызываем твой метод
    --         gui.set_render_order(0) -- Возвращаем приоритет в базу
    --     end
    --
    -- elseif message_id == hash("refresh") then
    --     if self.container_window and self.container_window:is_visible() then
    --         self.container_window.inventory_grid:refresh()
    --     end
    -- end       
end

function on_input(self, action_id, action)
    if drag_manager.is_dragging() then
        -- Обновление позиции
        if action_id == nil or action_id == h_touch then
            drag_manager.update(action.x, action.y)
        end

        -- Попытка дропа
        if action_id == h_touch and action.released then
            if self.container_window.inventory_grid:on_drop(action.x, action.y) then
                return true
            end
        end
    end

    return self.druid:on_input(action_id, action) -- Можно вернуть return обратно
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
