-- test_script.lua
function init(self)
    print("Test object initialized")
    msg.post(".", "acquire_input_focus")
end

function on_message(self, message_id, message, sender)
    print("Test object received:", message_id)
    
    if message_id == hash("toggle_interactable_highlight") then
        print("Test object HIGHLIGHT!")
        if message.show then
            go.set_scale(vmath.vector3(2, 2, 1), go.get_id())
        else
            go.set_scale(vmath.vector3(1, 1, 1), go.get_id())
        end
    end
end
