go.property("uid", hash("")) -- Для предметов из редактора
go.property("item_id",  hash("unknown"))
go.property("amount", 1)

local locales = require("main.modules.data.locales.locale_manager")
local interaction = require("main.modules.interaction")
local items_db = require "main.modules.data.items_db"
local broadcast = require("main.modules.system.broadcast")
local world_items_state = require("main.modules.game_state.world_items_state")

-- Вспомогательные функции для HUD
local function show_highlight(self, go_id)
    go.set_scale(vmath.vector3(1.2, 1.2, 1), go_id)
    -- Показываем текст
    msg.post(msg.url(nil, go_id, "item_name"), "enable")
end

local function hide_highlight(self, go_id)
    go.set_scale(vmath.vector3(1, 1, 1), go_id)
    -- Скрываем текст
    msg.post(msg.url(nil, go_id, "item_name"), "disable")
end

local function apply_item_visual(self)
    local data = items_db.get_item(self.item_id)
    if data then
        local sprite_url = msg.url(nil, go.get_id(), "sprite")
        sprite.play_flipbook(sprite_url, hash(data.animation))
        label.set_text("#item_name", locales.get(data.name_key))
        if self.amount > 1 then
            label.set_text("#amount", self.amount)
        end
    end
end

function init(self)
    msg.post(".", "acquire_input_focus")

    -- СОХРАНЯЕМ ID этого конкретного предмета в self
    self.go_id = go.get_id()

    -- 1. ЛОГИКА UID (как в контейнере)
    if self.uid == hash("") then
        local p = go.get_position()
        -- Генерируем "паспорт" для предмета из редактора
        local s_uid = string.format("i_%d_%d", p.x, p.y)
        self.uid = hash(s_uid)
        
        -- 2. РЕГИСТРИРУЕМ В СТЕЙТЕ
        -- Если его там еще нет (первый запуск), добавляем вручную
        if not world_items_state.get_item_by_uid(s_uid) then
            world_items_state.registry[s_uid] = {
                item_id = tostring(self.item_id),
                pos = { x = p.x, y = p.y },
                amount = self.amount or 1
            }
        end
    end    -- self.amount = 1
    self.is_interactable = true

    if self.item_id ~= hash("unknown") then
        apply_item_visual(self)
    end

    -- Скрываем имя по умолчанию
    msg.post("#item_name", "disable")

    -- Передаем этот ID внутрь замыкания
    self.broadcast_handler = function(data)
        if data.message_id == hash("toggle_interactable_highlight") then

            if data.show then
                show_highlight(self, self.go_id) -- передаем сохраненный ID
            else
                hide_highlight(self, self.go_id)
            end
        end
    end

    broadcast.subscribe("world_events", self.broadcast_handler)

    print("Lootable item type:", self.type)
    self.highlight_node = nil
    self.normal_color = vmath.vector4(1,1,1,1)
end

function final(self)
    broadcast.unsubscribe("world_events", self.broadcast_handler)
end

function update(self, dt)

end

function late_update(self, dt)

end

function fixed_update(self, dt)

end

function on_message(self, message_id, message, sender)
    -- if message_id == hash("pickup_item") then
    --     -- Пересылаем в GUI. message содержит item_id и amount
    --     msg.post("hud#gui", "add_to_inv", message)
    --     -- Удаляем предмет из мира
    --     go.delete(sender)
    -- end

    if message_id == hash("set_item_id") then
        self.item_id = message.item_id
        self.amount = message.amount or 1
        self.uid = message.uid -- СОХРАНЯЕМ UID!

        local data = items_db.get_item(self.item_id)
        local item_name = locales.get(data.name_key)
        if data then
            label.set_text("#item_name", item_name)
            if self.amount > 1 then
                label.set_text("#amount", self.amount)
            end
        end
    end

    if message_id == hash("click") then
        interaction.handle_click(self, 50, function()
            -- ПЕРЕДАЕМ UID в мир, чтобы вычеркнуть его из базы сохранений
            msg.post("/world#world", "pickup_item", {
                item_id = self.item_id,
                amount = self.amount,
                uid = self.uid -- ВАЖНО!
            })
        end)
    end
end

function on_reload(self)

end
