---@class LoaderScriptInstance : table
---@field pending_position vector3|nil Отложенные координаты игрока для телепортации
---@field pending_action_bars any[]|nil       Отложенный кэш панелей способностей

---@param self LoaderScriptInstance
function init(self)
    msg.post(".", "acquire_input_focus")
    print("LOADER STARTED. PROXY ID: game_proxy")
    -- Обращаемся к прокси через #
    msg.post("#game_proxy", "load")
end

---@param self LoaderScriptInstance
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)
    if message_id == hash("reload_game") then
        self.pending_position = message.saved_position
        msg.post("#game_proxy", "unload")

    elseif message_id == hash("proxy_unloaded") then
        timer.delay(0.1, false, function() msg.post("#game_proxy", "load") end)

    elseif message_id == hash("proxy_loaded") then
        msg.post(sender, "enable")
        msg.post(sender, "acquire_input_focus")

        -- Сбрасываем кэш панелей
        self.pending_action_bars = nil
        -- 1. СЦЕНА ГОТОВА: Проверяем, откуда мы стартуем
        if self.pending_position then
            -- 💾 А) ВЕТКА ЗАГРУЗКИ СЕЙВА:
            -- Втыкаем игрока ровно туда, где он сохранился в JSON!
            msg.post("game_scene:/player", "teleport_to", { position = vmath.vector3(self.pending_position.x,  self.pending_position.y, self.pending_position.z) })
           -- msg.post("game_scene:/world#world", "spawn_all_saved_items")
            self.pending_position = nil
        else
            -- 🌟 Б) ВЕТКА НОВОЙ ИГРЫ (Твой новый Data-Driven канон):
            -- Мы даем один фрейм задержки, чтобы world_controller успел в своем первом update
            -- заспавнить чанк Meadows, и точка спавна успела прописать себя в память!
            timer.delay(0.01, false, function()
                local map_config = require("main.modules.data.map_config")
                -- Ищем в оперативной памяти точку, которую мы на прехабе Meadows обозвали hash("mage_start")
                local spawn_point = map_config.get_spawn_point(hash("default_start"))

                if spawn_point then
                    -- Нашли точку! Телепортируем игрока в её честные мировые координаты чанка!
                    msg.post("game_scene:/player", "teleport_to", { position = spawn_point.position })

                    -- Здесь у тебя есть ПОЛНЫЙ доступ ко всем твоим go.property!
                    print("ЭВЕНТ СТАРТА: ID чанка =", spawn_point.zone_id, "Метка сюжета =", spawn_point.story_milestone)

                    -- Можешь запустить стартовый ролик или взвести квестовый флаг в бэкенд historias!
                    if spawn_point.story_milestone == hash("prologue_done") then
                        -- ...
                    end
                else
                    -- Страховка: если точка не зарегистрировалась, ставим в дефолтный центр
                    msg.post("game_scene:/player", "teleport_to", { position = vmath.vector3(1126, 725, 1) })
                end
            end)
        end
    end
end



